version = 1

# ---------------------------
# Python (Backend - Flask + SQLAlchemy + SQLite)
# ---------------------------
[[analyzers]]
name = "python"
enabled = true

[analyzers.meta]
runtime_version = "3.x"
type_checker = "mypy"
style_guide = "pep8"

[[transformers]]
name = "black"
enabled = true

[[transformers]]
name = "isort"
enabled = true

# Report backend test coverage (pytest + coverage.py)
[[test_coverage]]
analyzer = "python"
version = 1

# ---------------------------
# Python (Core runtime)
# ---------------------------
[[analyzers]]
name = "python"
enabled = true

[analyzers.meta]
runtime_version = "3.x"
type_checker = "mypy"
style_guide = "pep8"


[[transformers]]
name = "black"
enabled = true

[[transformers]]
name = "isort"
enabled = true

[[transformers]]
name = "ruff"
enabled = true

# Report backend test coverage (pytest + coverage.py)
[[test_coverage]]
analyzer = "       python"
coverage_report_path = "coverage.xml"

# --      -------------------------
# SQL (For migrations, scripts, raw queries)
# -------------------      --------
[[analyzers]]
name = "sql"
enabled = true

[analyzers.meta]
dialect = "sqlite"
