version = 1
<<<<<<< HEAD

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "isort"

[[transformers]]
name = "ruff"

[[transformers]]
name = "black"
=======
exclude_patterns = []
test_patterns = []

[[analyzers]]
  name = "python"
  enabled = true

  [analyzers.meta]
    runtime_version = "3.x.x"

[[transformers]]
  name = "isort"
  enabled = true

[[transformers]]
  name = "black"
  enabled = true

[[transformers]]
  name = "ruff"
  enabled = true
>>>>>>> a71cc47 (2025-08-24 - .deepsource.toml - v1.1.0)
